#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__AUTHOR__ = "Victor Nieves Sanchez"
__COPYRIGHT__ = "Copyright 2018, Victor Nieves Sanchez"
__CREDITS__ = ["Victor Nieves Sanchez"]
__LICENSE__ = "GPL"
__VERSION__ = "1.0.0"
__PYTHON__= "3.6.4"
__EMAIL__ = "vnievess@gmail.com"


import sys
from colors import color
from backend import backend

class Game(object):
	def __init__(self):
		name = ""
		item = ""
		lastAnswer = ""
		world = ""

def checkPyVersion():
	if sys.version_info < (3,0):
		print(color("Por favor use la version 3.0 o superior", fg= 'red', style= 'bold'))
		sys.exit(1)

def loading():
	backend.sayToUser(color(".CARGANDO ENTORNO.", fg='green'))
	backend.sleep(0.5)
	backend.sayToUser(color(".                .", fg ='green'))
	backend.sleep(1)
	backend.sayToUser(color("..              ..", fg ='green'))
	backend.sleep(0.6)
	backend.sayToUser(color("...            ...", fg ='green'))
	backend.sleep(1)
	backend.sayToUser(color("....          ....", fg ='green'))
	backend.sleep(0.5)
	backend.sayToUser(color(".....        .....", fg ='green'))
	backend.sleep(0.5)
	backend.sayToUser(color("......      ......", fg ='green'))
	backend.sleep(1)
	backend.sayToUser(color(".......    .......", fg ='green'))
	backend.sleep(1)
	backend.sayToUser(color("........  ........", fg= 'green'))
	backend.sleep(0.5)
	backend.sayToUser(color("..................", fg= 'green'))
	backend.sleep(0.5)
	backend.sayToUser(color("..................", fg= 'green'))
	backend.sleep(0.5)
	checkPyVersion()
	backend.sayToUser(color("....INICIANDO.....", fg ='green'))
	backend.sleep(1)
	backend.sayToUser(color("..................", fg= 'green'))
	backend.sleep(0.7)

def intro():
	backend.sayToUser("Son las 05:00AM, estás en un garito de mala muerte con tus colegas y vas algo “feliz”.")
	backend.sleep(1.5)
	backend.sayToUser("Te quieres ir a casa. Y ¿Qué harás? ...")
	backend.sleep(1)
	answer = backend.askToUser("1) Le dices a tus colegas que ya te marchas.\n2) Haces bomba de humo.")
	while (answer != "1") and (answer != "2"):
		backend.nonValidAnswer()
		answer = backend.askToUser("1) Le dices a tus colegas que ya te marchas.\n2) Haces bomba de humo.")
	backend.sayToUser("De camino a casa te encuentras con una persona encapuchada. No consigues ver su cara.")
	backend.sleep(1.5)
	backend.sayToUser("El te habla:")
	backend.sleep(1)
	backend.sayDialogue("- ¡Ey! Joven, ¿quieres fumar del porro?")
	backend.sleep(1)
	backend.sayToUser("Te ofrece un porro. ¿Lo aceptas?")
	answer = backend.askToUser("1) Si.\n2) No.")
	while (answer != "1") and (answer != "2"):
		backend.nonValidAnswer()
		answer = backend.askToUser("1) Si.\n2) No.")
	return answer

def badEnding():
	backend.sayDialogue("- ¡¿COOOOOMOO?! Vaya gilipollas eres. ¡Ala, a mamarla!")
	backend.sleep(1.1)
	backend.sayToUser("Sigues caminando de camino a casa. Consigues a duras penas llegar a tu cama.")
	backend.sleep(1.3)
	backend.sayToUser("Te tumbas y te duermes.")
	backend.sleep(2)
	backend.sayToUser(".")
	backend.sleep(1)
	backend.sayToUser("..")
	backend.sleep(1)
	backend.sayToUser("...")
	backend.sleep(1)
	backend.sayToUser(color("FIN",fg = 'blue', style = 'bold+underline'))
	backend.sleep(1)
	backend.byeInfo()
	sys.exit(0)

def continuation1():
	backend.sayDialogue("- Toma toma, a disfrutarlo. (Te da el porro y se va haciendo la croqueta).")
	backend.sleep(1)
	backend.sayToUser(".")
	backend.sleep(1)
	backend.sayToUser("..")
	backend.sleep(1)
	backend.sayToUser("...")
	backend.sleep(1)
	backend.sayToUser("Llegas a tu casa a duras penas. Te comes un güen bocadillo de lomo puta madre.")
	backend.sleep(1)
	backend.sayToUser("Te bebes un vasito de leche con Nesquick.")
	backend.sleep(1)
	backend.sayDialogue("(PORQUE EL  COLACAO ES UNA PUTA MIERDA)")
	backend.sleep(0.7)
	backend.sayToUser("Te vas a la cama y te duermes ipso facto.")
	backend.sleep(1)
	backend.sayToUser(".")
	backend.sleep(1)
	backend.sayToUser("..")
	backend.sleep(1)
	backend.sayToUser("...")
	backend.sleep(1)
	backend.sayToUser("Ya es de día.")
	backend.sleep(0.5)
	backend.sayToUser("Te despiertas en una habitación, pero no es la tuya. ")
	backend.sleep(1)
	backend.sayDialogue("¿Dónde coño te acostaste anoche? ¿Era tu casa?")
	backend.sleep(1)
	backend.sayToUser("Como sea. Te pones a mirar a tu alrededor.") 
	backend.sleep(1)
	backend.sayToUser("Ves lo que parece una cabina britanica de policía azul.")
	backend.sleep(1)
	backend.displayImage("Cabina extraña.", "images/Dwho.jpg")
	backend.sleep(1)
	backend.sayToUser("¿Entras en la máquina?")
	answer = backend.askToUser("1) Si.\n2) No.")
	while (answer != "1") and (answer != "2"):
		backend.nonValidAnswer()
		answer = backend.askToUser("1) Si.\n2) No.")
	if answer == '2':		
		backend.sayDialogue("- !Pero vamos a ver, gilí!¿Qué eres león o güevón?. Entras igual porque así lo quiero yo.")
	backend.sleep(1.3)
	backend.sayToUser("Entras en la máquina.")
	backend.sleep(1)
	

def insertName():
	return backend.askToUser("Te pide que introduzcas tu nombre:")
	
def choseWorld():
	backend.sayToUser("Ves que hay una serie de destinos disponibles.")
	backend.sleep(0.5)
	backend.sayToUser("El mundo de la bella y la bestia, Dubai, el puticlub Las Flores, Nuevo Londo . . . ")
	backend.sleep(1.5) 
	backend.sayToUser("Eliges un destino.")
	backend.sleep(0.5)
	answer = backend.askToUser("1) El mundo de la bella y la bestia.\n2) Dubai.\n3) El puticlub Las Flores.\n4) Nuevo Londo.")
	while (answer != "1") and (answer != "2") and (answer != "3") and (answer != "4"):
			backend.nonValidAnswer()
			answer = backend.askToUser("1) El mundo de la bella y la bestia.\n2) Dubai.\n3) El puticlub Las Flores.\n4) Nuevo Londo.")
	if answer == "1":
		world = "El mundo de la bella y la bestia"
	elif answer == "2":
		world = "Dubai"
	elif answer == "3":
		world = "El puticlub Las Flores"
	else:
		world = "Nuevo Londo"
	backend.sayToUser("Eliges como destino " + world + ".")
	return world
		
def continuation2():
	backend.sayToUser("Pero, de repente escuchas sonidos extraños.")
	backend.sleep(1)
	backend.sayToUser("Saltan chispas, hay turbulencias, la cabina empieza a girar.")
	backend.sleep(1)
	backend.sayToUser("¡PIIIIIMBA!")
	backend.sleep(1)
	backend.sayToUser("Te pegas la hostia padre.")
	backend.sleep(1)
	backend.sayToUser("La cabina ha parado de moverse.")
	backend.sleep(1)
	backend.sayToUser("Está tirada de manera horizontal.")
	backend.sleep(1)
	backend.sayToUser("No puedes salir. Lo intentas pero no hay manera.")
	backend.sleep(1)
	backend.sayToUser("Escuchas rido fuera.")
	backend.sleep(1)	
	backend.sayDialogue("- ¡BURP Oh joder, que hace esto aquí.")
	backend.sleep(1)
	backend.sayDialogue("¡BURP! No veo una mierda, vaya ciego llevo.")
	backend.sleep(1)
	backend.sayToUser("Alguien está moviendo la cabina. ")
	backend.sleep(1)
	backend.sayToUser("La pone de pie.")
	backend.sleep(1)
	backend.sayToUser("Abren la puerta.")
	backend.sleep(1)
	backend.sayDialogue("- ¡BURP! Oh joder Morty, ¿eres tú?.")
	backend.sleep(1)
	backend.sayDialogue("Soy yo, Rick.")
	backend.displayImage("Rick", "images/rick.jpg")
	backend.sayDialogue("¡BURP! Pensé que te habían capturado esos carcelarios cabrones del universo C-177.")
	backend.sleep(1.5)
	backend.sayToUser("¿Le sigues la corriente a Rick diciendo que eres Morty?")
	answer = backend.askToUser("1) Si.\n2) No.")
	while (answer != "1") and (answer != "2"):
		backend.nonValidAnswer()
		answer = backend.askToUser("1) Si.\n2) No.")
	backend.sleep(1)
	return answer

def chooseItem1():
	backend.sayDialogue("- Bien, Morty ¡BURP!, continuemos con nuestra misión.")
	backend.sleep(1)
	backend.sayDialogue("Ah, por cier-¡BURP!-to, tienes que ir preparado, coge algo de esta bolsa.")
	backend.sleep(1.5)
	backend.sayToUser("Abres la bolsa y te encuentras una serie de objetos.")
	backend.sleep(1)
	backend.sayToUser("¿Cuál eliges?")
	backend.sleep(1)
	#backend.displayImage("1) Nada", "images/nada.png")
	backend.displayImage("2) Pistola de rayos", "images/prayos.png")
	backend.displayImage("3) La caja misteriosa", "images/mbox.jpg")
	item = backend.askToUser("1) No coger nada.\n2) Coger una pistola de rayos marca ACME.\n3) Coger la caja misteriosa.")
	while item != "1" and item !="2" and item !="3":
		backend.nonValidAnswer()
		item = backend.askToUser("1) No coger nada.\n2) Coger una pistola de rayos marca ACME.\n3) Coger la caja misteriosa.")
	backend.sleep(1)
	if item == "1":
		item = "Nada"
	elif item == "2":
		item = "Pistola de rayos"
	else:
		item = "Caja misteriosa"
	backend.sayToUser("Eliges como item: " + item + ".")
	return item

def continuationMorty(item):
	backend.sayDialogue("- Vale Morty, como ya sabes, nuestra misión ¡BURP! es asesinar a ... ")
	backend.sleep(1)
	backend.sayDialogue("Adolfo Lincoln, quien tiene un ejercito de Mortys y Ricks arios y quieren dominar este universo ¡BURP!.")
	backend.sleep(1.5)
	backend.displayImage("Adolfo Lincoln", "images/adolfL.jpg")
	backend.displayImage("Rick y Morty de este universo", "images/rymN.png")
	backend.sayDialogue("Mi contacto, me ha informado de que al amanecer del quinto día ¡BURP!, osea ...")
	backend.sleep(1.5)
	backend.sayDialogue("Hoy no, MAÑAAAA!-¡BURP! ... ")
	backend.sleep(1)
	backend.sayDialogue("¡JODER MORTY! ¡Es verdad! llevamos aquí cuatro días ya.")
	backend.sleep(1.5)
	backend.sayDialogue("Démonos prisa. Ese cabrón está en aquel edificio a lo lejos.")
	backend.sleep(1.5)
	backend.sayToUser("Os poneís a correr como locos.")
	backend.sleep(1)
	backend.sayToUser("Entraís en el edificio que os indicó el informador.")
	backend.sleep(1)
	backend.sayToUser("Por lo que parece no hay enemigos, bueno ... es normal.")
	backend.sleep(1)
	backend.sayToUser("¿Qué se puede esperar de un ejercito de Mortys? ")
	backend.sleep(1)
	backend.sayToUser("Subís a la parte más alta del edificio, a la azotea. ")
	backend.sleep(1)
	backend.sayToUser("Y allí está Adolfo Lincoln.")
	backend.sleep(1)
	backend.displayImage("Adolfo Lincoln", "images/adolfL.jpg")
	backend.sayToUser("Empieza un tiroteo desenfrenado entre Rick y Adolfo.")
	backend.sleep(1)
	backend.sayToUser("¡¡Oh, no!!")
	backend.sleep(1)
	backend.sayToUser("Rick sale herido y pierde el arma.")
	backend.sleep(1)
	backend.sayToUser("¡Es tu momento! ")
	if item == "Nada":
		backend.sayToUser("Un Morty ario se confunde y salva a nuestro Rick (recibiendo un disparo a camara lenta) pensando que era su compañero.")
		backend.sleep(2)
		backend.sayToUser("Rick consigue hacerse con el arma de ese Morty y consigue disparar entre ceja y ceja de Adolfo Lincoln.")
		backend.sleep(2)
	elif item == "Pistola de rayos":
		backend.sayToUser("Sacas la pistola de rayos que habías cogido y disparas a Adolfo Lincoln.")
		backend.displayImage("Pistola de rayos", "images/prayos.png")
	else: #caja misteriosa
		backend.sayToUser("Abres la caja misteriosa y dentro hay un licor especial.")
		backend.displayImage("La caja misteriosa", "images/mbox.jpg")
		backend.displayImage("La botella de dentro", "images/vodka.jpg")
		backend.sayToUser("Se lo lanzas a Rick.")
		backend.sleep(1)
		backend.sayToUser("Rick se tira tal eructo que de la fuerza del mismo, empuja a Adolfo Lincoln.")
		backend.sleep(1.5)
		backend.sayToUser("Con la fortuna que se cae por el balcón y muere en el acto.")
		backend.sleep(1)
		backend.sayToUser("Con la misión terminada, vaís de camino a la nave de Rick.")
		backend.sleep(1)
		backend.sayToUser("Os encontraís con Morty, The Real Morty.")
		backend.displayImage("Morty", "images/morty.png")
		backend.sayDialogue("-¡BURP! Pero que coño está pasando Morty, bueno, ¡BURP! Mortys.")
		backend.sleep(1.5)
		backend.sayToUser("¿Le dices la verdad?")
		answer = backend.askToUser("1) Si.\n2) No.")
		while (answer != "1") and (answer != "2"):
			backend.nonValidAnswer()
			answer = backend.askToUser("1) Si.\n2) No.")
		backend.sleep(1)
		return answer

def contarVerdad(nombre):
	backend.sayDialogue("- ¡Que no eres Morty!")
	backend.sleep(1)
	backend.sayDialogue("¿Y porqué no me dijiste la verdad? ")
	backend.sleep(1)
	backend.sayDialogue("¿Cuál es tu nombre?, el de verdad quiero decir.")
	backend.sleep(1)
	backend.sayDialogue("¡BURP! Bueno " + nombre + ", como me has ayudado y Morty está bien, te arreglaré la nave espacial.")
	backend.sleep(1.5)
	backend.sayDialogue("Así podrás volver a casa.")
	backend.sleep(1)
	goodEnding()

def noContarVerdad():
	backend.sayToUser("Rick, temiendo que ese Morty sea un Morty enemigo, le dispara con la pistola de rayos. ")
	backend.sleep(1.5)
	backend.sayToUser("Morty muere en el acto.")
	backend.sleep(1)
	backend.sayToUser("Tal acto te impacta. Por lo que piensas en decir la verdad.")
	backend.sleep(1)
	backend.sayToUser("¿Dices la verdad?")
	answer = backend.askToUser("1) Si.\n2) No.")
	while (answer != "1") and (answer != "2"):
		backend.nonValidAnswer()
		answer = backend.askToUser("1) Si.\n2) No.")
	backend.sleep(1)
	if answer == "1":
		backend.sayDialogue("- ¡Oh mierda! ¡BURP! Ya lo podías haber dicho antes. ")
		backend.sleep(1)
		backend.sayDialogue("Es el octavo Morty que mato esta semana. ")
		backend.sleep(1)
		backend.sayDialogue("En fin, usaré la máquina genética para hacer otra copia de él.")
		backend.sleep(1)
		backend.sayDialogue("Entonces, ¿Esa nave es tuya? ")
		backend.sleep(0.5)
		backend.sayDialogue("Parecía algo dañada. Te ayudaré a repararla.")
		backend.sleep(1)
		backend.sayToUser("Rick te repara la nave, y ya puedes volver a ella.")
		backend.sleep(1)
		goodEnding()
	else:	
		backend.sayToUser("Sutilmente, le pides a Rick que eche un vistazo a la nave en la que te encontró. ")
		backend.sleep(1.5)
		backend.sayToUser("Al ver tal tecnología, decide llevársela.")
		backend.sleep(1)
		backend.sayToUser(".")
		backend.sleep(0.5)
		backend.sayToUser("..")
		backend.sleep(0.5)
		backend.sayToUser("...")
		backend.sleep(0.5)
		backend.sayToUser("Ya en el universo C-137 (el universo de Rick). ")
		backend.sleep(1)
		backend.sayToUser("Rick arregló la nave y tú, a sus espaldas te montaste en ella y te largaste. ")
		backend.sleep(1.5)
		goodEnding()

def goodEnding():
	backend.sayToUser("Montas en la nave.")
	backend.sleep(1)
	backend.sayToUser("De nuevo, te pide que elijas un destino.")
	backend.sleep(1)
	backend.sayToUser(".")
	backend.sleep(0.5)
	backend.sayToUser("..")
	backend.sleep(0.5)
	backend.sayToUser("...")
	backend.sleep(0.5)
	backend.sayToUser("Continuará ...")
	backend.sleep(1)
	backend.sayToUser("... o no ...")
	backend.sleep(1)
	backend.byeInfo()

def main():
	try:
		gameData = Game()
		loading()
		gameData.lastAnswer = intro()
		if gameData.lastAnswer == "2":
			badEnding()
			sys.exit(0)	
		else:	
			continuation1()	
			gameData.name = insertName()
			backend.sleep(0.5)
			gameData.world = choseWorld()
			backend.sleep(0.5)
			gameData.lastAnswer = continuation2()
			if gameData.lastAnswer == '1':
				gameData.item = chooseItem1()
				gameData.lastAnswer = continuationMorty(gameData.item)
				if gameData.lastAnswer == '1':
					contarVerdad(gameData.name)
				else:
					noContarVerdad()
			else:
				print("PASSSSSSS")
				pass
				#2 no eres morty
	except KeyboardInterrupt:
		backend.keyboardInterruptText()

if __name__ == "__main__":
	main()


