#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = "Victor Nieves Sanchez"
__copyright__ = "Copyright 2018, Victor Nieves Sanchez"
__credits__ = ["Victor Nieves Sanchez"]
__license__ = "GPL"
__version__ = "1.0.1"
__python__= "3.6.4"
__email__ = "vnievess@gmail.com"

import backend
from colors import color
import sys

class Game(object):
	def __init__(self):
		name = ""
		item = ""
		lastAnswer = ""
		world = ""

def checkPyVersion():
	if sys.version_info < (3,0):
		print(color("Por favor use la version 3.0 o superior", fg= 'red', style= 'bold'))
		sys.exit(1)

def loading():
	backend.backend.sayToUser(color(".CARGANDO ENTORNO.", fg='green'))
	backend.backend.sleep(0.5)
	backend.backend.sayToUser(color(".                .", fg ='green'))
	backend.backend.sleep(1)
	backend.backend.sayToUser(color("..              ..", fg ='green'))
	backend.backend.sleep(0.6)
	backend.backend.sayToUser(color("...            ...", fg ='green'))
	backend.backend.sleep(1)
	backend.backend.sayToUser(color("....          ....", fg ='green'))
	backend.backend.sleep(0.5)
	backend.backend.sayToUser(color(".....        .....", fg ='green'))
	backend.backend.sleep(0.5)
	backend.backend.sayToUser(color("......      ......", fg ='green'))
	backend.backend.sleep(1)
	backend.backend.sayToUser(color(".......    .......", fg ='green'))
	backend.backend.sleep(1)
	backend.backend.sayToUser(color("........  ........", fg= 'green'))
	backend.backend.sleep(0.5)
	backend.backend.sayToUser(color("..................", fg= 'green'))
	backend.backend.sleep(0.5)
	backend.backend.sayToUser(color("..................", fg= 'green'))
	backend.backend.sleep(0.5)
	checkPyVersion()
	backend.backend.sayToUser(color("....INICIANDO.....", fg ='green'))
	backend.backend.sleep(1)
	backend.backend.sayToUser(color("..................", fg= 'green'))
	backend.backend.sleep(0.7)

def intro():
	backend.backend.sayToUser("Son las 05:00AM, estás en un garito de mala muerte con tus colegas y vas algo “feliz”.")
	backend.backend.sleep(1.5)
	backend.backend.sayToUser("Te quieres ir a casa. Y ¿Qué harás? ...")
	backend.backend.sleep(1)
	answer = backend.backend.askToUser("1) Le dices a tus colegas que ya te marchas.\n2) Haces bomba de humo.")
	while (answer != "1") and (answer != "2"):
		backend.backend.nonValidAnswer()
		answer = backend.backend.askToUser("1) Le dices a tus colegas que ya te marchas.\n2) Haces bomba de humo.")
	backend.backend.sayToUser("De camino a casa te encuentras con una persona encapuchada. No consigues ver su cara.")
	backend.backend.sleep(1.5)
	backend.backend.sayToUser("El te habla:")
	backend.backend.sleep(1)
	backend.backend.sayDialogue("- ¡Ey! Joven, ¿quieres fumar del porro?")
	backend.backend.sleep(1)
	backend.backend.sayToUser("Te ofrece un porro. ¿Lo aceptas?")
	answer = backend.backend.askToUser("1) Si.\n2) No.")
	while (answer != "1") and (answer != "2"):
		backend.backend.nonValidAnswer()
		answer = backend.backend.askToUser("1) Si.\n2) No.")
	return answer

def badEnding():
	backend.backend.sayDialogue("- ¡¿COOOOOMOO?! Vaya gilipollas eres. ¡Ala, a mamarla!")
	backend.backend.sleep(1.1)
	backend.backend.sayToUser("Sigues caminando de camino a casa. Consigues a duras penas llegar a tu cama.")
	backend.backend.sleep(1.3)
	backend.backend.sayToUser("Te tumbas y te duermes.")
	backend.backend.sleep(2)
	backend.backend.sayToUser(".")
	backend.backend.sleep(1)
	backend.backend.sayToUser("..")
	backend.backend.sleep(1)
	backend.backend.sayToUser("...")
	backend.backend.sleep(1)
	backend.backend.sayToUser(color("FIN",fg = 'blue', style = 'bold+underline'))
	backend.backend.sleep(2)
	sys.exit(0)

def continuation1():
		backend.backend.sayDialogue("- Toma toma, a disfrutarlo. (Te da el porro y se va haciendo la croqueta).")
		backend.backend.sleep(1)
		backend.backend.sayToUser(".")
		backend.backend.sleep(1)
		backend.backend.sayToUser("..")
		backend.backend.sleep(1)
		backend.backend.sayToUser("...")
		backend.backend.sleep(1)
		backend.backend.sayToUser("Llegas a tu casa a duras penas. Te comes un güen bocadillo de lomo puta madre.")
		backend.backend.sleep(1)
		backend.backend.sayToUser("Te bebes un vasito de leche con Nesquick.")
		backend.backend.sleep(1)
		backend.backend.sayDialogue("(PORQUE EL  COLACAO ES UNA PUTA MIERDA)")
		backend.backend.sleep(0.7)
		backend.backend.sayToUser("Te vas a la cama y te duermes ipso facto.")
		backend.backend.sleep(1)
		backend.backend.sayToUser(".")
		backend.backend.sleep(1)
		backend.backend.sayToUser("..")
		backend.backend.sleep(1)
		backend.backend.sayToUser("...")
		backend.backend.sleep(1)
		backend.backend.sayToUser("Ya es de día.")
		backend.backend.sleep(0.5)
		backend.backend.sayToUser("Te despiertas en una habitación, pero no es la tuya. ")
		backend.backend.sleep(1)
		backend.backend.sayDialogue("¿Dónde coño te acostaste anoche? ¿Era tu casa?")
		backend.backend.sleep(1)
		backend.backend.sayToUser("Como sea. Te pones a mirar a tu alrededor.") 
		backend.backend.sleep(1)
		backend.backend.sayToUser("Ves lo que parece una cabina britanica de policía azul.")
		backend.backend.sleep(1)
		backend.backend.displayImage("Cabina extraña.", "images/Dwho.jpg")
		backend.backend.sleep(1)
		backend.backend.sayToUser("¿Entras en la máquina?")
		answer = backend.backend.askToUser("1) Si.\n2) No.")
		while (answer != "1") and (answer != "2"):
			backend.backend.nonValidAnswer()
			answer = backend.backend.askToUser("1) Si.\n2) No.")
		return answer

def insertName():
	return backend.backend.askToUser("Te pide que introduzcas tu nombre:")
	
def choseWorld():
	backend.backend.sayToUser("Ves que hay una serie de destinos disponibles.")
	backend.backend.sleep(0.5)
	backend.backend.sayToUser("El mundo de la bella y la bestia, Dubai, el puticlub Las Flores, Nuevo Londo . . . ")
	backend.backend.sleep(1.5) 
	backend.backend.sayToUser("Eliges un destino.")
	backend.backend.sleep(0.5)
	answer = backend.backend.askToUser("1) El mundo de la bella y la bestia.\n2) Dubai.\n3) El puticlub Las Flores.\n4) Nuevo Londo.")
	while (answer != "1") and (answer != "2") and (answer != "3") and (answer != "4"):
			backend.backend.nonValidAnswer()
			answer = backend.backend.askToUser("1) El mundo de la bella y la bestia.\n2) Dubai.\n3) El puticlub Las Flores.\n4) Nuevo Londo.")
	if answer == "1":
		world = "El mundo de la bella y la bestia"
	elif answer == "2":
		world = "Dubai"
	elif answer == "3":
		world = "El puticlub Las Flores"
	else:
		world = "Nuevo Londo"
	backend.backend.sayToUser("Eliges como destino " + world + ".")
	return world
		
def main():
	try:
		gameData = Game()
		loading()
		gameData.lastAnswer = intro()
		if gameData.lastAnswer == "2":
			badEnding()
			sys.exit(0)	
		else:
			gameData.lastAnswer = continuation1()
			if gameData.lastAnswer == '2':		
				backend.backend.sayDialogue("- !Pero vamos a ver, gilí!¿Qué eres león o güevón?. Entras igual porque así lo quiero yo.")
				backend.backend.sleep(1.3)
			backend.backend.sayToUser("Entras en la máquina.")		
			gameData.name = insertName()
			backend.backend.sleep(0.5)
			gameData.world = choseWorld()
			backend.backend.sleep(0.5)
			print("CONTINUA")
			#pero de repente escuchas...
	except KeyboardInterrupt:
		backend.backend.keyboardInterruptText()
if __name__ == "__main__":
	main()


